#!/usr/bin/env python3
"""Kozy Care — Project Handover & Operations Guide (client + developer).

Report route: ReportLab body + HTML/Playwright cover (Template 01 HUD),
merged via pypdf. TOC via TocDocTemplate + multiBuild.
Palette: cascade (auto-generated, gold family — on-brand for Kozy).
"""
import hashlib
import os
import sys

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (CondPageBreak, HRFlowable, KeepTogether,
                                PageBreak, Paragraph, SimpleDocTemplate,
                                Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

from pdf import install_font_fallback

# ── Fonts ────────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f4f3')
SECTION_BG    = colors.HexColor('#f1f0ee')
CARD_BG       = colors.HexColor('#edece8')
TABLE_STRIPE  = colors.HexColor('#f0efee')
HEADER_FILL   = colors.HexColor('#524b34')
COVER_BLOCK   = colors.HexColor('#62593d')
BORDER        = colors.HexColor('#ccc4ac')
ICON          = colors.HexColor('#8b7945')
ACCENT        = colors.HexColor('#93761e')
ACCENT_2      = colors.HexColor('#54abc8')
TEXT_PRIMARY  = colors.HexColor('#242320')
TEXT_MUTED    = colors.HexColor('#77756e')

# ── Page geometry (symmetric margins) ────────────────────────────────────
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_THRESHOLD = AVAIL_H * 0.25

OUT = '/home/z/my-project/download/Kozy-Care-Project-Handover.pdf'
DOC_TITLE = 'Kozy Care — Project Handover & Operations Guide'

# ── Styles ───────────────────────────────────────────────────────────────
S = {}
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5,
                           leading=16.5, alignment=TA_JUSTIFY,
                           textColor=TEXT_PRIMARY, spaceAfter=8)
S['bodyL'] = ParagraphStyle('BodyL', parent=S['body'], alignment=TA_LEFT)
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=19, leading=24,
                         textColor=HEADER_FILL, spaceBefore=18, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=13.5, leading=18,
                         textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
S['part'] = ParagraphStyle('Part', fontName='FreeSerif', fontSize=23, leading=28,
                           textColor=ACCENT, spaceBefore=6, spaceAfter=2)
S['partsub'] = ParagraphStyle('PartSub', fontName='FreeSerif', fontSize=11,
                              leading=15, textColor=TEXT_MUTED, spaceAfter=14)
S['bullet'] = ParagraphStyle('Bullet', parent=S['bodyL'], leftIndent=16,
                             bulletIndent=4, spaceAfter=5)
S['thead'] = ParagraphStyle('THead', fontName='FreeSerif', fontSize=9.5,
                            leading=12.5, textColor=colors.white,
                            alignment=TA_LEFT)
S['tcell'] = ParagraphStyle('TCell', fontName='FreeSerif', fontSize=9.5,
                            leading=13, textColor=TEXT_PRIMARY,
                            alignment=TA_LEFT)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5,
                              leading=11, textColor=TEXT_MUTED,
                              alignment=TA_CENTER, spaceBefore=3, spaceAfter=6)
S['callout'] = ParagraphStyle('Callout', fontName='FreeSerif', fontSize=10,
                              leading=15, textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['toc0'] = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5,
                           leading=20, textColor=TEXT_PRIMARY)
S['toc1'] = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10,
                           leading=16, leftIndent=18, textColor=TEXT_MUTED)


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def heading(text, style, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/><b>{text}</b>', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def h1(story, text):
    story.append(CondPageBreak(H1_THRESHOLD))
    story.append(heading(text, S['h1'], level=0))
    story.append(HRFlowable(width='100%', thickness=1.6, color=ACCENT,
                            spaceBefore=0, spaceAfter=10))


def h2(story, text):
    story.append(CondPageBreak(AVAIL_H * 0.12))
    story.append(heading(text, S['h2'], level=1))


def para(story, text, style='body'):
    story.append(Paragraph(text, S[style]))


def bullets(story, items):
    for it in items:
        story.append(Paragraph(it, S['bullet'], bulletText='•'))
    story.append(Spacer(1, 4))


def table(story, header, rows, ratios, caption=None):
    """Safe table: Paragraph cells, proportional widths, centered, striped."""
    widths = [r * AVAIL_W * 0.98 for r in ratios]
    assert sum(widths) <= AVAIL_W + 0.5, 'table overflow'
    data = [[Paragraph(f'<b>{c}</b>', S['thead']) for c in header]]
    for row in rows:
        data.append([Paragraph(c, S['tcell']) for c in row])
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5.5),
        ('LINEBELOW', (0, 0), (-1, 0), 0.8, HEADER_FILL),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_STRIPE if i % 2 == 1 else colors.white))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 10))
    story.append(t)
    if caption:
        story.append(Paragraph(caption, S['caption']))
    story.append(Spacer(1, 8))


def callout(story, title, body_html):
    """Accent callout box for key notes."""
    inner = [
        [Paragraph(f'<b>{title}</b>',
                   ParagraphStyle('ct', parent=S['callout'], fontSize=10.5,
                                  textColor=HEADER_FILL))],
        [Paragraph(body_html, S['callout'])],
    ]
    t = Table(inner, colWidths=[AVAIL_W * 0.96])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3.2, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (0, 0), 8),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 9),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
    ]))
    story.extend([Spacer(1, 6), t, Spacer(1, 10)])


# ── Header / footer ──────────────────────────────────────────────────────
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.1)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    canvas.drawString(MARGIN, 0.5 * inch, 'Prepared for Kozy Care · Lagos · August 2026')
    canvas.drawRightString(PAGE_W - MARGIN, 0.5 * inch, f'Page {doc.page}')
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.restoreState()


# ══ STORY ════════════════════════════════════════════════════════════════
story = []

toc = TableOfContents()
toc.levelStyles = [S['toc0'], S['toc1']]
story.append(Paragraph('<b>Table of Contents</b>',
                       ParagraphStyle('TT', parent=S['h1'], spaceBefore=0)))
story.append(HRFlowable(width='100%', thickness=1.6, color=ACCENT,
                        spaceBefore=0, spaceAfter=14))
story.append(toc)
story.append(PageBreak())

# ── Part I ───────────────────────────────────────────────────────────────
story.append(Paragraph('<b>PART I — GUIDE FOR THE CLIENT</b>', S['part']))
story.append(Paragraph('Everything you need to run Kozy Care day-to-day, no developer required.',
                       S['partsub']))
story.append(HRFlowable(width='100%', thickness=0.7, color=BORDER, spaceAfter=6))

# ── 1. Executive summary ──
h1(story, '1. Executive Summary')
para(story, 'Kozy Care is live. Your customers can book a pickup in about two minutes at '
     '<b>https://kozycare.ng</b> — with or without an account — pay by bank transfer or card, '
     'track their order in a personal portal, and leave a review that flows straight into your '
     'admin console. Your team manages the whole business from one admin dashboard: orders, '
     'payment verification, customer records, pricing, and reviews. Riders run pickups and '
     'deliveries from a mobile-optimised driver app with GPS geofencing across twelve Lagos '
     'service zones. Alongside the software, you now own a complete brand and print kit: a '
     'production logo system, A5 flyers, an A3 poster, and business cards in two colourways, '
     'all print-ready with crop marks and bleed.')
para(story, 'This document is written for two readers. <b>Part I</b> is for you, the business '
     'owner: what you own, how to access it, how to run daily operations, and a short list of '
     'actions only you can take (security, payment keys, and a few account settings). '
     '<b>Part II</b> is for whoever develops the platform next: architecture, the deployment '
     'pipeline, environment variables, subsystem documentation, known limitations, and a '
     'prioritised roadmap. Keep this document with your business records — it is the single '
     'source of truth for the handover.')
para(story, 'Two things to internalise immediately. First, the platform is fully functional '
     'today, but three revenue-relevant integrations — online card payment (Paystack), SMS '
     'notifications (Termii), and the verified email sender (Brevo) — are built and waiting '
     'for API keys that only you can provide. Second, several credentials were shared '
     'over chat during development; rotating them is the single most urgent security action '
     'on your list, and it takes about ten minutes.')

# ── 2. What you own ──
h1(story, '2. What You Own — Platforms & Live Assets')
para(story, 'The table below is the complete inventory of what this project has delivered. '
     'Everything in it is yours: the code is in your GitHub account, the hosting and database '
     'run on your Vercel and Supabase accounts, the domain is registered to you, and every '
     'design file ships with editable sources. Nothing is locked to a third party or to the '
     'original developer.')
table(story,
      ['Asset', 'Where it lives', 'What it does'],
      [['Customer website', 'https://kozycare.ng', 'Landing page, pricing, testimonials, booking'],
       ['Guest booking flow', 'https://kozycare.ng/book', 'Book a pickup without creating an account'],
       ['Customer portal', 'https://kozycare.ng/portal', 'Order tracking, invoices, reviews'],
       ['Admin console', 'https://kozycare.ng/admin', 'Orders, payments, CRM, pricing, reviews, finance'],
       ['Driver app', 'https://kozycare.ng/driver', 'Route view with GPS geofencing and swipe confirmations'],
       ['Rider recruitment', 'https://kozycare.ng/join-riders', 'Public application page for new riders'],
       ['Source code', 'github.com/R2deetwo/Kozy-Dryclean', 'The entire application (public repository)'],
       ['Brand & print kit', 'kozy-brand folder (delivered with this handover)', 'Logo system, flyers, poster, business cards, brand sheet'],
       ['Domain', 'kozycare.ng (your registrar)', 'Points to Vercel; www redirects to the apex domain']],
      [0.20, 0.36, 0.44],
      caption='Table 1 — Inventory of live assets and where each one lives.')
para(story, 'The website is fully responsive and has been verified end-to-end on production: '
     'a real guest order was placed, priced from the live catalogue, and tracked through the '
     'payment-verification queue. Search engine basics are in place — sitemap.xml, robots.txt, '
     'canonical URLs, and a branded social-share image — so Google can index the site and '
     'WhatsApp link previews show the Kozy card. Vercel Analytics is installed but needs one '
     'click from you to start collecting traffic data (see action item 5).')

# ── 3. Accounts & security ──
h1(story, '3. Accounts, Access & Security')
para(story, 'Seven online accounts together run the whole operation. You should be the owner '
     'of record on all of them, with the login credentials stored in your password manager. '
     'The table lists each account, what it does, and what to check on day one.')
table(story,
      ['Account', 'Purpose', 'Day-one check'],
      [['GitHub (R2deetwo)', 'Source code repository', 'Confirm you can sign in and see the Kozy-Dryclean repo'],
       ['Vercel', 'Hosting & deploys (project: kozy-dryclean)', 'Confirm the kozycare.ng domain shows as valid in Settings → Domains'],
       ['Supabase', 'Postgres database (all business data)', 'Confirm sign-in; the database is managed, no daily work needed'],
       ['Upstash', 'Redis for rate limiting', 'Confirm sign-in; no daily work needed'],
       ['Brevo', 'Transactional email (receipts, resets, updates)', 'Verify concierge@kozy.ng as a sender (action item 2)'],
       ['Paystack', 'Online card payments', 'Add API keys in Vercel (action item 3)'],
       ['Termii', 'SMS notifications', 'Add API key in Vercel (action item 4)'],
       ['Domain registrar', 'kozycare.ng DNS', 'Records already point to Vercel — no change needed']],
      [0.18, 0.38, 0.44],
      caption='Table 2 — The accounts that run Kozy Care and what to verify on each.')
h2(story, '3.1 Security — read this first')
para(story, 'During development, a GitHub personal access token and a Vercel token were shared '
     'over chat to push code and trigger deployments. Chat history is not a secure place for '
     'credentials. Both tokens work as of handover day and must be treated as potentially '
     'exposed. Rotating them takes minutes and locks the window permanently: generate new '
     'tokens, update the Vercel token anywhere you use it, and revoke the old ones. Until '
     'this is done, anyone with the chat history could push code to your repository or '
     'trigger deployments. This is action item 1 for a reason.')
para(story, 'Going forward, treat secrets with three simple habits. Never paste tokens into '
     'chat or email; share them through a password manager or a secure note that expires. '
     'Never commit secrets to the repository — GitHub push protection is enabled and has '
     'already blocked accidental leaks twice, but it is a safety net, not a strategy. Finally, '
     'all runtime secrets belong in the Vercel environment-variable settings (or the .env '
     'file on your own machine), never in the code itself.')

# ── 4. Daily operations ──
h1(story, '4. Running the Business Day-to-Day')
para(story, 'Everything below happens inside the admin console at kozycare.ng/admin and needs '
     'no developer. Sign in with your admin account; the console is organised into views '
     'reachable from the sidebar.')
h2(story, '4.1 Orders — the daily rhythm')
para(story, 'New bookings appear in the orders view, which you can flip between a Kanban board '
     'and a list. A typical day: open the console in the morning and look for orders sitting '
     'in PAYMENT PENDING VERIFICATION (these are bank-transfer customers who have paid and '
     'are waiting for you to confirm their transfer in the payment queue). Once verified, the '
     'order moves along the pipeline (picked up → cleaning → out for delivery → delivered) '
     'either automatically as riders confirm stops in the driver app, or manually from the '
     'order modal. Every status change can trigger a customer email automatically, so the '
     'customer stays informed without you lifting a finger.')
h2(story, '4.2 Money — verification, refunds, and finance')
para(story, 'The payment queue shows every pending transfer with the order number and amount; '
     'match it against your bank statement and approve. Card payments (once Paystack is '
     'activated) verify themselves through a webhook and need no manual step. The finance '
     'view charts revenue over time, and invoices are generated per order and available to '
     'the customer in their portal. Refund handling follows your published refund policy '
     '(the /refunds page is live) — refunds for card payments are initiated from your '
     'Paystack dashboard, and bank-transfer refunds are a manual transfer from your bank.')
h2(story, '4.3 Customers, reviews, and pricing')
para(story, 'The CRM view lists every customer with their order history. Reviews arrive from '
     'two places: the Rate button customers see on delivered orders in their portal, and the '
     'public review form. New reviews wait in the reviews view for your approval before they '
     'appear in the landing-page carousel — nothing goes public without you. Pricing lives in '
     'the settings view: change any item price and the landing page, booking wizard, and '
     'future invoices all pick it up, because they all read from the same server-side '
     'catalogue. This is also where your bank-account details for transfer payments are '
     'maintained.')
callout(story, 'The one-minute price check',
        'Prices on the printed flyer were synced with the website on 28 August 2026 '
        '(including Sneakers White ₦1,500 / Coloured ₦1,000 and sneaker restoration from '
        '₦5,000). If you change prices in settings later, the website updates instantly — '
        'the flyer does not. Reprint flyers only after a big price change, or ask a '
        'developer to regenerate the artwork in minutes from the editable sources.')

# ── 5. Client action items ──
h1(story, '5. Your Action Items')
para(story, 'Nine items, in priority order. Items 1–5 are quick account settings; items 6–9 '
     'are business decisions. None require a developer, though a developer can help with 3 '
     'and 4 if you prefer.')
table(story,
      ['#', 'Action', 'Where / how'],
      [['1', '<b>Rotate the GitHub and Vercel tokens</b> (shared over chat during development)',
        'GitHub → Settings → Developer settings → Tokens; Vercel → Settings → Tokens. Revoke old, create new'],
       ['2', 'Verify concierge@kozy.ng as an email sender', 'Brevo → Senders & IP → add and verify the domain/address'],
       ['3', 'Activate online card payment', 'Paystack dashboard → Settings → API Keys → add Secret Key + Webhook Secret in Vercel env vars'],
       ['4', 'Activate SMS notifications', 'Termii dashboard → copy API key into Vercel env var TERMII_API_KEY'],
       ['5', 'Enable web analytics', 'Vercel project → Analytics tab → click Enable (script is already installed)'],
       ['6', 'Honour the printed offers', '15% off first order; free pickup & delivery applies to the first order only'],
       ['7', 'Personalise the business cards (optional)', 'Add a name/title via the editable HTML sources in the kit'],
       ['8', 'Decide on a brand-sheet refresh (optional)', 'Current sheet documents the previous logo generation; colours and type rules still apply'],
       ['9', 'Cancel the test order KZ-02150959', 'Admin console → orders → the order labelled "E2E Test (safe to cancel)"']],
      [0.05, 0.38, 0.57],
      caption='Table 3 — Client to-do list, priority order. Items 1–5 unlock existing features.')
para(story, 'Why items 3 and 4 matter most commercially: the online payment flow is fully '
     'built — customers choose "Pay Online — Card", get redirected to Paystack, and the '
     'payment confirms itself via webhook — but until the keys are set the button politely '
     'explains online payment is not configured and offers bank transfer instead. Every day '
     'the keys are missing is a day some customers abandon the transfer hassle. SMS works '
     'the same way: pickup and delivery alerts are written and wired, silent until the '
     'Termii key arrives.')

# ── 6. Marketing & print kit ──
h1(story, '6. Marketing & Print Kit')
para(story, 'The kozy-brand folder delivered with this handover contains the complete, '
     'print-ready marketing kit. Every piece exists in three forms: a print PDF with crop '
     'marks, bleed, and CMYK colour conversion for the press; a digital PDF without marks '
     'for WhatsApp, Instagram, and email; and an editable HTML source so any text change '
     'is a one-line edit followed by a re-render. The QR codes on every piece point to '
     'https://kozycare.ng and were decoded and verified before delivery.')
table(story,
      ['Piece', 'Spec', 'Contents'],
      [['Services flyer (A5, double-sided)', '148 × 210 mm + 3 mm bleed', 'Brand front; full price list back (19 items, live prices)'],
       ['Offer flyer (A5, single-sided)', '148 × 210 mm + 3 mm bleed', '15% off first order; value chips; QR'],
       ['Poster (A3)', '297 × 420 mm + 3 mm bleed', '"Three steps. Zero fuss." with offer band'],
       ['Business cards (85 × 55 mm)', 'Navy and white colourways, 2-sided', 'Brand front; phone, email, web, QR, both addresses back'],
       ['Logo system', 'SVG vectors + PNGs to 3824 px', 'Three lockups × three colourways + favicons + print PDF'],
       ['Brand sheet (A4)', '210 × 297 mm', 'Colour codes (HEX/RGB/CMYK + Pantone 871 C note), typography, usage rules']],
      [0.30, 0.28, 0.42],
      caption='Table 4 — The marketing kit at a glance.')
para(story, 'Three claims appear on the printed pieces and are part of your offer terms: '
     '<b>15% off the first order</b>, and <b>free pickup and delivery for the first order '
     'only</b> (marked with an asterisk and fine print on every piece that claims it). The '
     'turnaround language reads "express from 24 hours — regular service is 3–5 days", '
     'which matches how the service actually runs; the earlier "48-hour" wording was '
     'removed from all pieces. Both addresses — Ogombo and Paradise 3 Estate, Chevron — '
     'appear on every piece. When you hand files to a printer, give them only the PDFs '
     'inside each print/ folder; the kit README (README-PRINT.txt) contains the exact '
     'paper and finishing recommendations to pass on.')

# ── Part II ──────────────────────────────────────────────────────────────
story.append(CondPageBreak(H1_THRESHOLD))
story.append(Paragraph('<b>PART II — GUIDE FOR THE DEVELOPER</b>', S['part']))
story.append(Paragraph('Architecture, deployment, subsystems, and technical debt for whoever works on this next.',
                       S['partsub']))
story.append(HRFlowable(width='100%', thickness=0.7, color=BORDER, spaceAfter=6))

# ── 7. Architecture ──
h1(story, '7. Architecture Overview')
para(story, 'The application is a single Next.js 16 (App Router) project written in '
     'TypeScript 5, styled with Tailwind CSS 4 and shadcn/ui components, animated with '
     'Framer Motion. Data lives in Supabase Postgres behind Prisma; rate limiting and '
     'ephemeral counters use Upstash Redis over REST. Authentication is NextAuth with '
     'credentials and server-side sessions; role gates (customer / admin / driver) are '
     'enforced in middleware and in every API route that matters. The frontend reads '
     'server state through React Query hooks; Zustand remains only for genuinely ephemeral '
     'UI state and some legacy local persistence noted in section 10.')
table(story,
      ['Area', 'Where to look', 'Notes'],
      [['Landing page', 'src/components/customer/customer-landing.tsx', 'Hero, pricing (live server prices), guarantee, testimonials, footer'],
       ['Booking wizard', 'src/components/customer/booking-wizard.tsx', 'Retail + corporate flows, guest checkout, Paystack redirect'],
       ['Portal / admin / driver', 'src/app/portal, /admin, /driver', 'React Query against the API layer'],
       ['API routes', 'src/app/api/**', 'orders, payments, reviews, paystack, driver/location, auth'],
       ['Domain model', 'prisma/schema.prisma', 'Users, Orders, OrderItem, Payment, Review, DriverLocation, PriceCatalog, Settings'],
       ['Pricing', 'src/lib/types.ts (GARMENT_CATALOG) + src/lib/pricing-groups.ts', 'Single source shared by landing + wizard; DB PriceCatalog overrides at runtime'],
       ['Geofencing', 'src/lib/geo.ts', '12 Lagos service zones; rider GPS pings; enforcement radii'],
       ['Notifications', 'src/lib/notifications.ts', 'Branded email (Brevo) + SMS (Termii); env-gated, never throws'],
       ['Email templates', 'src/lib/email.ts', 'BREVO_VERIFIED_SENDER_EMAIL overrides the hardcoded fallback sender']],
      [0.20, 0.36, 0.44],
      caption='Table 5 — Codebase map: the fastest path into each subsystem.')
para(story, 'Three design decisions are worth knowing before you change anything. First, '
     'pricing has one source of truth: the server-side PriceCatalog, seeded from '
     'GARMENT_CATALOG, is what orders are actually charged at; the landing page and wizard '
     'display those same live prices, so a settings change propagates everywhere at once. '
     'Second, guest checkout is first-class: POST /api/orders accepts a guest payload, '
     'find-or-creates the customer, and creates the bank-transfer payment record atomically '
     'with the order. Third, everything degrades gracefully — missing Paystack or Termii '
     'keys never crash a flow, they surface clean 503s or silently skip SMS.')

# ── 8. Deployment ──
h1(story, '8. Deployment Pipeline & Environment')
h2(story, '8.1 How deploys actually work')
para(story, 'The single most important operational fact: <b>pushing to GitHub does not '
     'auto-deploy.</b> The Vercel Git integration is not connected (the webhook expects an '
     'org/repo/sha gitSource format that this repository arrangement does not provide). '
     'Production deploys are triggered through the Vercel REST API using a personal access '
     'token, with the team and project IDs below. The reference implementation is '
     'scripts/vercel_deploy.py in the repository, which wraps the whole sequence: create '
     'deployment from a target commit SHA, poll until READY, verify. Alternatively, click '
     'Deploy in the Vercel dashboard on any past commit — that path works too.')
table(story,
      ['Setting', 'Value'],
      [['Vercel project', 'kozy-dryclean (prj_BUv0ZqDMzsONFBQXXCgBJfmIN43e)'],
       ['Team', 'team_RJD4xe4C4h3TiJ3M3iEa8idV'],
       ['Build command', 'bun run build:vercel — runs prisma db push, then next build'],
       ['Effect of build command', 'Database schema auto-syncs on every deploy; no manual migrations needed'],
       ['Domains', 'kozycare.ng (primary) · www → apex 308 redirect · kozy-dryclean.vercel.app (legacy)'],
       ['Deploy trigger', 'POST /v13/deployments with teamId + gitSource SHA (see scripts/vercel_deploy.py)']],
      [0.28, 0.72],
      caption='Table 6 — Deployment configuration at a glance.')
h2(story, '8.2 Environment variables')
table(story,
      ['Variable', 'Status at handover', 'Purpose'],
      [['DATABASE_URL', 'set (Vercel)', 'Supabase Postgres connection string'],
       ['NEXTAUTH_SECRET / NEXTAUTH_URL', 'set — URL is https://kozycare.ng', 'Session signing and canonical base URL'],
       ['NEXT_PUBLIC_APP_URL', 'set — https://kozycare.ng', 'Client-side links, emails, Paystack callbacks'],
       ['UPSTASH_REDIS_REST_URL / TOKEN', 'set (Vercel)', 'Rate limiting on public API routes'],
       ['BREVO_API_KEY', 'set', 'Transactional email (auth flows, order updates)'],
       ['BREVO_VERIFIED_SENDER_EMAIL', 'not set — falls back to a personal Gmail', 'Set to concierge@kozy.ng once verified in Brevo'],
       ['PAYSTACK_SECRET_KEY / WEBHOOK_SECRET', 'not set', 'Activates online card payment + webhook verification'],
       ['TERMII_API_KEY', 'not set', 'Activates SMS notifications']],
      [0.30, 0.28, 0.42],
      caption='Table 7 — Environment variables. Secrets live only in Vercel settings, never in the repo.')
para(story, 'Local development is standard: clone, bun install, copy .env.example to .env, '
     'fill the values from Vercel (Settings → Environment Variables), and run bun run dev. '
     'Prisma talks to the same Supabase database, so treat local writes as production '
     'writes — create test data sparingly and clean it up. The scripts/ directory also '
     'contains create-admin.ts for seeding an admin account and a handful of maintenance '
     'utilities worth reading before running.')

# ── 9. Subsystems ──
h1(story, '9. Key Subsystems')
h2(story, '9.1 Reviews')
para(story, 'Reviews are database-backed end to end. Customers reach the review form from the '
     'Rate button on delivered orders (portal) or a review link; the form fetches order '
     'context from /api/reviews/order-context, which accepts only full order CUIDs (order '
     'numbers are rejected, preventing review hijacking), is IP rate-limited, and returns '
     'only the minimum fields needed. Public testimonials come from /api/reviews, which '
     'returns approved DB reviews, padded up to a minimum of six by marketing seed '
     'testimonials in src/lib/starter-testimonials.ts so the carousel never looks empty on '
     'day one. Moderation (approve / hide) happens in the admin console via '
     '/api/reviews/admin with role checks.')
h2(story, '9.2 Guest checkout & payments')
para(story, 'The booking wizard accepts guests (no account) with inline validation; if the '
     'email already belongs to a password-holding account, the API returns 409 and the UI '
     'offers sign-in. Bank-transfer payments are created atomically with the order and land '
     'in the admin verification queue. Card payment goes through POST /api/paystack/'
     'initialize — ownership-checked, creating a PENDING payment whose reference equals '
     'the order number, matching the webhook convention — then redirects to the Paystack '
     'hosted page; /payment/callback polls GET /api/paystack/verify and renders a branded '
     'result. The charge.success webhook marks the payment paid and fires notifications.')
h2(story, '9.3 Rider geofencing')
para(story, 'Riders GPS-ping /api/driver/location roughly once a minute while on shift. The '
     'server checks the ping against twelve Lagos service zones (src/lib/geo.ts): outside '
     'all zones, order activity pauses for that rider; inside, only stops within 12 km are '
     'offered and confirmations beyond 15 km from the stop\'s zone are rejected server-side. '
     'Stale or missing pings fall back to legacy behaviour, so the system never bricks the '
     'driver app. Zone radii are plain data — tuning them as the business grows is a '
     'one-file change.')
h2(story, '9.4 Notifications')
para(story, 'src/lib/notifications.ts sends branded HTML email through Brevo and SMS through '
     'Termii on order creation, guest account creation, status changes, and verified '
     'payments. Every send is wrapped so a failure never breaks the flow that triggered '
     'it. SMS is gated to actionable statuses (picked up, out for delivery, delivered) to '
     'respect the Termii balance. Until the keys are set, both channels stay dormant by '
     'design.')

# ── 10. Limitations ──
h1(story, '10. Known Limitations & Technical Debt')
para(story, 'Nothing on this list is broken for customers; these are the honest edges a '
     'successor should know about, roughly ordered by how soon they will bite.')
table(story,
      ['Item', 'Impact', 'Suggested fix'],
      [['Zustand still mirrors users/orders/payments into localStorage', 'Legacy demo architecture; can confuse debugging and show stale data after role switches', 'Finish the migration: React Query reads, Zustand for ephemeral UI only'],
       ['Admin notifications panel is localStorage-only', 'Notifications do not survive device changes', 'Back with a DB table + polling or server events'],
       ['GitHub → Vercel auto-deploy is not wired', 'Every deploy needs an API call or dashboard click', 'Fix the webhook gitSource format, or add a GitHub Action calling the Vercel deploy API'],
       ['Brand sheet documents the previous logo generation (v1.1)', 'Printed guidelines lag the v4 K mark now used on the site', 'Regenerate from scripts/kozy-brand/build_brand_sheet.py with the v4 lockup'],
       ['One test order (KZ-02150959) + guest test account in production data', 'Pollutes reporting slightly', 'Cancel the order in admin; delete the guest account'],
       ['Vercel Web Analytics not yet enabled', 'No traffic data collected yet', 'One click: project → Analytics → Enable'],
       ['Pricing seeds live in code + DB', 'A price change is trivial, but new items need a code edit', 'Move the full catalogue to the PriceCatalog table and manage purely from settings']],
      [0.34, 0.30, 0.36],
      caption='Table 8 — Known limitations, their impact, and the recommended fix.')

# ── 11. Roadmap & asset map ──
h1(story, '11. Suggested Roadmap & Asset Map')
para(story, 'If you take the platform forward in this order, each step builds on the last and '
     'none is wasted work:')
bullets(story, [
    '<b>Activate payments and SMS</b> (keys only) — the single highest-ROI step; both systems are complete and tested.',
    '<b>Enable analytics</b> and let two weeks of data accumulate before changing the funnel.',
    '<b>WhatsApp integration</b> — wa.me deep links on the landing page and in status notifications; Lagos customers live on WhatsApp.',
    '<b>Fix the deploy pipeline</b> — a GitHub Action calling the Vercel API on push, so future developers cannot forget the manual step.',
    '<b>Admin notifications to the database</b>, then retire the remaining Zustand localStorage persistence.',
    '<b>Brand sheet v4 refresh</b> and any print re-runs as prices evolve — the generator scripts make both cheap.'])
h2(story, '11.1 Where everything lives')
table(story,
      ['What', 'Where'],
      [['Application source', 'github.com/R2deetwo/Kozy-Dryclean (main branch is production)'],
       ['Deploy / env reference script', 'scripts/vercel_deploy.py in the repository'],
       ['Marketing kit (print + digital + sources)', 'kozy-brand/ folder delivered with this handover'],
       ['Marketing generator scripts', 'scripts/kozy-brand/ — build_v42.py, build_cards.py, render + package scripts'],
       ['Session worklog (full history)', 'worklog.md in the repository root'],
       ['This document', 'Kozy-Care-Project-Handover.pdf, delivered alongside the kit']],
      [0.40, 0.60],
      caption='Table 9 — Asset map: where to find everything referenced in this document.')
para(story, 'A final note on the worklog: worklog.md in the repository is the unedited, '
     'chronological record of every phase of this project — what was built, what was '
     'verified, what was deferred, and why. When this document and the worklog disagree, '
     'the worklog is the more detailed witness; when you need the reasoning behind any '
     'decision, it is almost certainly recorded there. Good luck — the platform is in '
     'good shape, and it is entirely yours.')

# ── Build ────────────────────────────────────────────────────────────────
doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=0.85 * inch,
    title=DOC_TITLE, author='Z.ai', creator='Z.ai',
    subject='Kozy Care platform and brand handover: client operations guide and developer documentation')
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print(f'OK body PDF built: {OUT}')
