#!/usr/bin/env python3
"""Kozy Care — Platform & Business Audit (Task 70). Body PDF via ReportLab."""
import os, sys, hashlib
sys.path.insert(0, '/home/z/my-project/skills/pdf/scripts')

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                 PageBreak, KeepTogether)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f0efed')
CARD_BG       = colors.HexColor('#ededea')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#665c3f')
COVER_BLOCK   = colors.HexColor('#6e6446')
BORDER        = colors.HexColor('#d8d2c0')
ICON          = colors.HexColor('#897a4e')
ACCENT        = colors.HexColor('#87702b')
ACCENT_2      = colors.HexColor('#7157bf')
TEXT_PRIMARY  = colors.HexColor('#22211f')
TEXT_MUTED    = colors.HexColor('#838079')
SEM_SUCCESS   = colors.HexColor('#3f8c59')
SEM_WARNING   = colors.HexColor('#ab8944')
SEM_ERROR     = colors.HexColor('#91524c')
SEM_INFO      = colors.HexColor('#4e759c')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

OUT = '/home/z/my-project/download/Kozy_Care_App_and_Business_Audit.pdf'
MARGIN = 0.9 * inch
AVAIL = A4[0] - 2 * MARGIN

# ----- Styles -----
h1 = ParagraphStyle('H1', fontName='FreeSerif', fontSize=17, leading=22,
                    textColor=HEADER_FILL, spaceBefore=6, spaceAfter=10)
h2 = ParagraphStyle('H2', fontName='FreeSerif', fontSize=12.5, leading=17,
                    textColor=TEXT_PRIMARY, spaceBefore=12, spaceAfter=6)
body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                      textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY)
bullet = ParagraphStyle('Bullet', parent=body, alignment=TA_LEFT, leftIndent=14,
                        bulletIndent=4, spaceAfter=5)
cell = ParagraphStyle('Cell', fontName='FreeSerif', fontSize=9, leading=12.5,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT)
cellc = ParagraphStyle('CellC', parent=cell, alignment=TA_CENTER)
th = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=12,
                    textColor=colors.white, alignment=TA_CENTER)
cap = ParagraphStyle('Cap', fontName='FreeSerif-Italic', fontSize=8.5, leading=11,
                     textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=4)
meta = ParagraphStyle('Meta', fontName='FreeSerif', fontSize=9, leading=12,
                      textColor=TEXT_MUTED, alignment=TA_LEFT)

story = []

def H1(text, num):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/><b>{num}&nbsp;&nbsp;{text}</b>', h1)
    p.bookmark_name, p.bookmark_level, p.bookmark_text, p.bookmark_key = key, 0, f'{num}  {text}', key
    story.append(p)

def H2(text):
    story.append(Paragraph(f'<b>{text}</b>', h2))

def P(text):
    story.append(Paragraph(text, body))
    story.append(Spacer(1, 7))

def B(text):
    story.append(Paragraph(f'•&nbsp;&nbsp;{text}', bullet))

def TBL(header, rows, ratios, caption=None):
    widths = [r * AVAIL for r in ratios]
    data = [[Paragraph(f'<b>{c}</b>', th) for c in header]]
    for r in rows:
        data.append([Paragraph(c, cell if i == 0 else cellc) for i, c in enumerate(r)])
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 10))
    story.append(t)
    if caption:
        story.append(Spacer(1, 4))
        story.append(Paragraph(caption, cap))
    story.append(Spacer(1, 12))

def KPIS(rows):
    """Scorecard row: area, score, note."""
    TBL(['Area', 'Score', 'Assessment'], rows, [0.30, 0.12, 0.58])

# ============================================================
# CONTENT — Chapter numbering: content starts at 1 (cover/TOC excluded)
# ============================================================

# ---- 1. Executive summary ----
H1('Executive Summary', '1')
P('This audit examined the Kozy Care platform end to end on 28 September 2026, immediately '
  'after the phase-70 release shipped to production. It covers the codebase (79 API routes, '
  '29 database models, the customer site, admin console and rider app), the production '
  'environment on Vercel and Supabase, the operating procedures that have accumulated across '
  '70 build phases, and the commercial position of the business in Lagos. The overall verdict '
  'is that the platform is in unusually good shape for its stage: the architecture is coherent, '
  'the security posture is above average for a small-team SaaS, and the operational tooling '
  '(branch health, payment verification, rider dispatch, marketing automation) is ahead of what '
  'most competitors in this market run on. The binding constraint is no longer software. It is '
  'demand generation and a small number of production-hardening items that should be closed '
  'before volume grows.')
P('Three events during this audit window materially changed the risk picture, all in the right '
  'direction. First, the VAPID keys for rider web-push notifications, which had been pending '
  'since phase 61, are now configured in production and verified live; stop notifications now '
  'reach riders without the dashboard being open. Second, the previously lost source of the '
  'phase-69 release (rider auto-dispatch and branch ownership) was recovered from the live '
  'deployment and reconciled into the repository, eliminating a silent rollback risk. Third, '
  'the standalone Shoe Club subscription and the company-branch numbers reset shipped and were '
  'verified live with an eleven-point production check. The remaining findings are graded in '
  'the table below and expanded through the report.')
KPIS([
    ['Platform architecture', '9 / 10', 'Modern single Next.js 16 monolith, 29 indexed Prisma models, graceful degradation on every integration'],
    ['Security', '7.5 / 10', 'Strong auth, RBAC, webhook signatures and CSP; rate limiting falls back per-instance because Redis is unset'],
    ['Reliability and ops', '7 / 10', 'Proven deploy recipe and self-healing seeds; schema-by-push and no verified backups need attention'],
    ['Customer experience', '8.5 / 10', 'Two-minute guest booking, plain-language plans, live tracking; notification depth still email-only'],
    ['Commercial engine', '8 / 10', 'Plans, club, coupons and automation are built and priced to undercut; zero subscribers means sales is the gap'],
    ['Data and analytics', '7 / 10', 'Branch attribution, response-time audit and epoch resets are live; reconciliation and backups are manual'],
])
story.append(Spacer(1, 6))
P('The single most important message of this audit: the product has outrun distribution. The '
  'membership engine has processed real orders and every renewal path is wired, yet the '
  'subscriber count on production remains zero, and the new Shoe Club will not sell itself. '
  'The 30-60-90 plan in the final chapter therefore weights sales motions above new features, '
  'with just enough hardening work to keep growth safe.')

# ---- 2. Scope and method ----
H1('Scope and Method', '2')
P('The audit combined static review of the repository at commit 61927bc with live probing of '
  'the production deployment that serves kozycare.ng, the Vercel project environment, and the '
  'production database schema and plan catalogue (read-only inspection and one idempotent '
  'migration that created the Shoe Club rows). Where the worklog records prior incidents, such '
  'as the newsletter timing drift or the rider notification gap, the fixes were re-verified '
  'rather than assumed. Browser-level checks against production confirmed the public plans '
  'surface, the Shoe Club section, and the rider push key endpoint. Nothing in this audit '
  'required destructive access: the branch numbers reset introduced in phase 70 was exercised '
  'against a local copy of the database, and production data was only read.')
P('Grading follows a simple convention. Findings marked P0 are things that could hurt the '
  'business within weeks if ignored, P1 within a quarter, and P2 are quality-of-life '
  'improvements worth scheduling when convenient. Scores in the executive table are relative '
  'to what a well-run early-stage laundry operation in Lagos should reasonably expect from '
  'its software, not relative to a venture-funded engineering org.')

# ---- 3. Platform health ----
H1('Platform Health', '3')
H2('Architecture and code quality')
P('The application is a single Next.js 16.1.1 App Router project on React 19 with Prisma 6.11 '
  'against Supabase Postgres, deployed as serverless functions on Vercel. This remains the '
  'right shape for the business: one deployable, one database, no service-to-service chatter '
  'to debug, and a build that completes in about a minute. The codebase shows real discipline '
  'for its size. TypeScript is strict with build errors deliberately not suppressed in the '
  'Next config; ESLint gates the same standard; a repository-wide search found zero TODO or '
  'FIXME markers; and only a dozen diagnostic console.log calls remain across the source tree. '
  'Every integration, from Brevo email to Paystack to web-push, degrades gracefully when its '
  'key is absent, which is why the site kept serving through every credential incident in the '
  'worklog.')
P('Data modelling is similarly tidy. The schema has 29 models with 60 explicit indexes, and '
  'lookup-heavy paths (orders by status and date, payments by order, push subscriptions by '
  'user) are covered. The self-seeding pattern used for app settings, the price catalogue, '
  'branches and subscription plans continues to pay off: a fresh database bootstraps itself '
  'into a working state with no manual seed step, which is exactly what saved this session '
  'after the sandbox reset.')
H2('Phase-70 additions verified this session')
B('Shoe Club: a second subscription family (SHOES) sold from the shoe-care section, with '
  'one-membership-per-family semantics, club-first shoe pickup routing, and an admin editor '
  'separate from the laundry tiers. Verified with 25 local assertions and 11 production checks.')
B('Branch numbers reset: an epoch field (statsResetAt) on company branches with a two-tap '
  'reset on the Branch Health card. Orders and payments are never deleted; the all-time line '
  'simply counts from the epoch, and franchise branches are refused server-side.')
B('Booking wizard scroll behaviour: every step transition now returns the customer to the '
  'top of the page (measured 2419 to 0 pixels in the verification battery).')
B('Rider web-push: the owner-pasted VAPID keys were confirmed live on production '
  '(available: true), closing a phase-61 action item.')

# ---- 4. Security ----
H1('Security and Compliance', '4')
P('Authentication is NextAuth with server-side sessions and bcrypt password hashing, and the '
  'console roles are policed twice: in middleware for pages and inside each API route via a '
  'requireRole guard. Fifty-seven of the seventy-nine route files carry explicit session '
  'checks, and the remaining ones are deliberately public (plan listings, health probes, '
  'tracking pixels). The staff lifecycle deserves particular praise: paused or revoked staff '
  'cannot obtain a session even with a correct password, and their audit trails are retained. '
  'The Paystack webhook verifies the x-paystack-signature HMAC before trusting any charge '
  'event, and card activation is idempotent through a unique reference per subscription.')
P('Transport and browser hardening are configured at the Next.js layer: HSTS, '
  'X-Frame-Options DENY, a strict referrer policy, a permissions policy that only grants '
  'camera and geolocation to the app itself, and a content-security-policy that allowlists '
  'only the domains the app actually talks to. Secrets live exclusively in Vercel '
  'environment storage, GitHub push protection has caught leaks before they landed, and the '
  'repository carries no credential material.')
H2('Findings')
B('P1 — rate limiting is per-instance in production. The Upstash Redis environment variables '
  'are present but empty, so the limiter silently falls back to in-memory counters inside '
  'each serverless instance. Booking and signup caps therefore hold per warm Lambda rather '
  'than globally. A free Upstash database and two environment values close this gap.')
B('P2 — a handful of public marketing endpoints (open and click trackers) accept unauthenticated '
  'writes with no rate limit. They are low-risk today because each write is a tiny row, but '
  'they should join the limiter before any high-volume campaign.')
B('P2 — there is no automated vulnerability scanning of dependencies. The stack is current '
  '(Next 16, React 19, Prisma 6), and a weekly audit run would keep it that way.')

# ---- 5. Reliability and operations ----
H1('Reliability and Operations', '5')
H2('Deployment pipeline')
P('The deploy recipe is now stable and documented in the README: commit to main, then ship '
  'source through the Vercel CLI or REST API with the project-scoped token, which cannot be '
  'validated with whoami but deploys correctly. This session shipped the phase-70 build in '
  'about one minute, aliased automatically to kozycare.ng, and applied the schema through the '
  'build itself. The historical footguns (dead tokens, missing project link, lost sandbox '
  'state) each have a written recovery path in the worklog, and the README now encodes them '
  'for the next operator.')
H2('Findings')
B('P1 — schema changes ship via prisma db push --accept-data-loss inside the build command. '
  'This has been convenient for seventy phases, but on a production database holding real '
  'payment records it is one misunderstood column away from an irreversible drop. Adopting '
  'Prisma migrate with reviewable migration files is a one-off switch.')
B('P1 — backups are assumed, not verified. Supabase makes automated backups available, but no '
  'restore has ever been rehearsed and no retention policy is written down. A monthly '
  'restore rehearsal into a scratch database converts this from a hope into a control.')
B('P2 — there is no staging environment. Every change lands in production, and local testing '
  'depends on the developer sandbox surviving. A Vercel preview deployment with a branched '
  'database would let risky work (pricing engine, webhook changes) be rehearsed first.')
B('P2 — error monitoring is not wired. SENTRY_DSN is empty, so runtime errors surface only '
  'when a customer complains. Even the free tier of an error tracker would change that.')

# ---- 6. Customer experience ----
H1('Customer Experience', '6')
P('The booking path remains the strongest surface: a guest can complete an order in roughly '
  'two minutes without an account, with an auto-saved draft, offer codes validated live '
  'server-side, a photo-condition step, and a stuck-payment banner that explains a failed '
  'transfer in plain words. The phase-70 scroll fix removes the last known irritation in the '
  'wizard: moving between steps now behaves like turning a page. The memberships page reads '
  'honestly to a non-specialist, with three kit-sized tiers, a persona strip, and a full '
  'per-item price list below, while the portal gives members live usage meters and one-tap '
  'perk booking.')
P('The new Shoe Club presentation follows the same plain-words doctrine: one section inside '
  'the existing shoe-care area, three cards named by what you get (1, 3 or 5 pairs a month), '
  'per-pair arithmetic printed on the card, and a competitor anchor line that makes the '
  'value obvious without naming anyone. Club members see a dedicated card in the portal with '
  'its own usage meter, booking button and independent cancellation, and a shoes-only '
  'customer is still invited to explore laundry plans rather than hitting a dead end.')
H2('Findings')
B('P1 — delivery-day communication is email-only in production. The Termii sender '
  'configuration exists but the API key is not set, so there are no SMS or WhatsApp messages '
  'on pickup and delivery days, which is when customers actually look at their phones. '
  'Enabling the existing SMS path, or moving to the WhatsApp Business API, is the highest '
  'impact customer-facing change available.')
B('P2 — the invoice view is a rendered page rather than a downloadable PDF, which some '
  'corporate clients will ask for when invoicing through expense systems.')

# ---- 7. Commercial audit ----
H1('Commercial and Business Audit', '7')
H2('Pricing and product ladder')
P('The retail card is priced at the accessible end of the Lagos market (sneakers at 1,000 to '
  '1,500 naira, shirts from 500, corporate laundry from 800 per kilogram), while the three '
  'membership tiers at 30,000, 50,000 and 80,000 naira a month are sized by physical kit '
  'volume, which keeps fulfilment honest. The Shoe Club extends the ladder downward with '
  'entry at 1,000 naira a month, which matters: the cheapest laundry plan is thirty times '
  'the price of the cheapest club month, so the club is the natural first product for a '
  'student or young professional who cannot yet commit to weekly laundry. Every number on '
  'every surface is admin-editable at runtime, and price edits sync Paystack recurring plans '
  'when the keys are configured.')
H2('Competitive position (researched this session)')
TBL(['Lagos operator', 'Model', 'Observed pricing', 'Kozy answer'],
    [['Care by Sneaklin', 'App-based sneaker laundry, 72h turnaround',
      'Sneaker clean 8,000; leather 7,000; suede 12,000; premium packages 15,000-25,000 per pair',
      'Shoe Club from 800-1,000 naira a pair with pickup and delivery included'],
     ['LBN Laundry (Lekki)', 'Instagram-led cleaning and restoration', 'Around 10,000 naira per pair or pack',
      'Standard sneaker clean at 1,000-1,500 naira a-la-carte'],
     ['K-Kleen (Lekki)', 'Walk-in sneaker service with published list', 'Specialist per-pair pricing above laundry norms',
      'Restoration from 5,000 with free assessment and quote-first approval']],
    [0.20, 0.24, 0.32, 0.24],
    'Table 1. Lagos shoe-care competitors researched 28 September 2026 versus the Kozy position.')
P('The gap is large enough to be the marketing story rather than a fight over percentage '
  'points: Lagos sneaker laundries charge seven to eight thousand naira for a single basic '
  'clean, while the club lands between 800 and 1,000 naira per pair with collection and '
  'return included. Kozy can hold this position because shoes ride the existing rider routes '
  'and hub batches, which the dedicated specialists pay standalone logistics to replicate.')
H2('The demand gap')
P('Everything commercial is built: plans, club, coupons with windows and caps, a '
  'calendar-synced newsletter engine, loyalty and referral ledgers, and Paystack recurring '
  'billing with transfer verification as the local fallback. Production currently shows zero '
  'memberships and a modest order book across two branches. The software cannot close that '
  'gap; only a sales motion can. The rider fleet itself is an underused channel: every '
  'delivery is a doorstep moment with a printed flyer in the bag, and the WhatsApp broadcast '
  'list built from order history is the cheapest acquisition channel available. The phase-69 '
  'rider response league now makes it possible to tie acquisition pushes to the riders who '
  'actually deliver on time.')
H2('Franchise readiness')
P('The console now distinguishes company sites from partner sites end to end: gold treatment '
  'and partner chips, a revenue-share ledger through the Partners tab, and a numbers-reset '
  'that deliberately refuses franchise branches because their ledger is contractual. The '
  'expansion memo delivered in phase 69 remains the strategy document; the software side of '
  'a first franchise is ready, and the remaining work is contractual and operational rather '
  'than technical.')

# ---- 8. Data and analytics ----
H1('Data and Analytics', '8')
P('The reporting spine hardened considerably across phases 69 and 70. Every order is '
  'branch-attributed at creation, the historical book was backfilled to Chevron, response '
  'times from assignment to acceptance are captured for the rider league, and the new epoch '
  'reset lets the owner restart a company branch counters without touching financial '
  'records. Finance views filter by branch and date range, and Branch Health surfaces the '
  'amber conditions that actually precede complaints: unrouted pickups, receipts waiting '
  'over twenty-four hours, and branches with no riders.')
H2('Findings')
B('P2 — there is no automated daily reconciliation between verified payments and the order '
  'book. The queues make manual verification reliable, but a scheduled report that totals '
  'verified payments per branch per day and emails exceptions would remove the last manual '
  'finance ritual.')
B('P2 — marketing analytics track opens and clicks but stop short of attribution to orders. '
  'Coupon codes partially close this; adding a campaign tag to the booking source would '
  'close it fully.')

# ---- 9. Recommendations ----
H1('Prioritized Recommendations', '9')
P('The table below consolidates every finding from the preceding chapters into one ranked '
  'list. P0 items should be started this week, P1 within the month, and P2 items are '
  'scheduled work that improves life without protecting anything urgent.')
TBL(['#', 'Priority', 'Recommendation', 'Effort'],
    [['1', 'P0', 'Run the sales motion: rider-delivered flyers with the Shoe Club offer, a WhatsApp broadcast to the order history, and a hotel/corporate push for per-kilogram laundry. The product is ready; distribution is not.', 'Ongoing'],
     ['2', 'P0', 'Confirm rider push with two or three real riders this week (keys are now live): toggle notifications in the rider app Account tab, assign a stop, and verify the phone buzzes with the browser closed.', 'Half day'],
     ['3', 'P1', 'Configure Upstash Redis (free tier) so booking, signup and payment rate limits hold across all serverless instances.', 'One hour'],
     ['4', 'P1', 'Switch the production build from prisma db push --accept-data-loss to reviewed Prisma migrations, and rehearse a Supabase restore into a scratch database once, then monthly.', 'One day'],
     ['5', 'P1', 'Enable SMS or WhatsApp delivery-day notifications (the Termii path is built; only the key is missing).', 'One hour plus review'],
     ['6', 'P2', 'Stand up a staging deployment with a branched database for risky changes, and wire the existing E2E battery to run on deploy.', 'Two days'],
     ['7', 'P2', 'Add an error tracker (free Sentry tier), dependency audit in CI, downloadable invoice PDFs, and rate limits on the remaining public trackers.', 'Scattered'],
     ['8', 'P2', 'Introduce a weekly numbers ritual for the owner: Branch Health all-time lines, rider response league, and subscriber counts, fifteen minutes every Monday.', 'Habit']],
    [0.05, 0.10, 0.75, 0.10],
    'Table 2. Ranked recommendations from the audit.')

# ---- 10. Roadmap ----
H1('The 30-60-90 View', '10')
P('The first thirty days belong to distribution and the two production-hardening items that '
  'guard it: the Redis rate limits and the migration switch. The Shoe Club launch is the '
  'marketing moment; the undercut against dedicated sneaker laundries is so large that the '
  'story tells itself on any Lagos timeline, and the club entry price is low enough for '
  'impulse subscription. The rider fleet should carry the offer physically, and the '
  'newsletter engine should carry it digitally, with the Independence-week campaign already '
  'scheduled as the template.')
P('Days thirty to sixty are the subscriber sprint. Concrete targets make the engine real: '
  'twenty-five Essentials households and fifteen Shoe Club members inside eight weeks would '
  'prove both funnels and generate the renewal data the admin screens are waiting for. The '
  'hotel and corporate channel deserves one dedicated push with the per-kilogram offer, '
  'because a single hotel contract out-earns dozens of retail members at zero incremental '
  'software cost. This is also the window for SMS or WhatsApp notifications, because '
  'delivery-day presence is what corporate clients remember.')
P('Days sixty to ninety turn outward: the first franchise pilot using the ownership tooling '
  'that is now live, an evaluation of a third company site on the mainland using the branch '
  'health data as evidence, and a review of this audit with whatever the numbers say by '
  'then. The pattern across all three windows is the same one this audit found everywhere '
  'else: the platform keeps being ready slightly before the business needs it to be, which '
  'is exactly the order a young company wants those two things in.')

# ---- build ----
class TocDoc(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            self.notify('TOCEntry', (getattr(flowable, 'bookmark_level', 0),
                                     getattr(flowable, 'bookmark_text', ''),
                                     self.page,
                                     getattr(flowable, 'bookmark_key', '')))

doc = TocDoc(OUT, pagesize=A4,
             leftMargin=MARGIN, rightMargin=MARGIN,
             topMargin=0.8 * inch, bottomMargin=0.8 * inch,
             title='Kozy Care — Platform & Business Audit',
             author='Kozy Care Engineering')

def footer(canvas, doc_):
    canvas.saveState()
    canvas.setFont('FreeSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.5 * inch, 'Kozy Care · Platform & Business Audit · September 2026')
    canvas.drawRightString(A4[0] - MARGIN, 0.5 * inch, f'Page {doc_.page}')
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(MARGIN, 0.62 * inch, A4[0] - MARGIN, 0.62 * inch)
    canvas.restoreState()

from reportlab.platypus.tableofcontents import TableOfContents
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=10.5, leading=16, leftIndent=6,
                   textColor=TEXT_PRIMARY),
]
toc_heading = ParagraphStyle('TOCH', fontName='FreeSerif', fontSize=15, leading=20,
                             textColor=HEADER_FILL, spaceAfter=12)

story.insert(0, PageBreak())
story.insert(0, toc)
story.insert(0, Paragraph('<b>Table of Contents</b>', toc_heading))

doc.multiBuild(story, onFirstPage=footer, onLaterPages=footer)
print('BODY OK:', OUT)
